#!/usr/bin/env -S sh -c "echo >&2 \"Error: You are running this script instead of sourcing it. Make sure to use it as 'source setenv' or '. setenv', otherwise its settings won't take effect.\"; exit 1"

# first argument can be (e.g. 'source setenv -q'):
# -q : do not show banner text on configuration success

# Get the directory where this script reside using a trick (works differently on bash and zsh)
# On bash, the current script's name is in 'BASH_SOURCE[0]'
if [ "$BASH_VERSION" != "" ]; then # for BASH
  dir=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)
elif [ "$ZSH_VERSION" != "" ]; then # on zsh the script name is in '$0'
  dir=$(cd $(dirname $0) && pwd)
else # on any other SH compatible shell we assume that the current working directory is the OMNeT++ root directory
  dir=$(pwd)
fi

#FIXME: change to fogchains
# check if dir is really pointing to an omnet++ installation dir
if [ ! -d $dir/src -o ! -d $dir/simulations ]; then
    echo "Error: '$dir' does not look like an fogchain root directory"
    return 1
fi

# check if omnet environement is set
if [ -z "$__omnetpp_root_dir" ] ; then
    echo "Error: OMNeT++ environemnt is not set"
    return 1
fi

#FIXME: set environemnt

export __fogchains_root_dir=$dir
dir=

if [ "$1" != "-q" ]; then
  echo "Environment for fogchains in directory '$__fogchains_root_dir' is ready."

fi

