#!/bin/sh
cd `dirname $0`
EXEPATH=${__omnetpp_root_dir}/samples/fogchains/src
if [ -n "${DEBUG}" ]
then
    echo "debug mode on"
    EXENAME=${EXEPATH}/fogchains_dbg
else
    echo "debug mode off"
    EXENAME=${EXEPATH}/fogchains
fi
${EXENAME} -n .:../src $*
#../src/fogchains_dbg -n .:../src $*
# for shared lib, use: opp_run -l ../src/fogchains -n .:../src $*
