#!/bin/sh
cd `dirname $0`
SRCPATH=${__omnetpp_root_dir}/samples/fogchains/src
SIMPATH=${__omnetpp_root_dir}/samples/fogchains/simulations
EXEPATH=${__omnetpp_root_dir}/samples/fogchains/src
if [ -n "${DEBUG}" ]
then
    echo "debug mode on"
    EXENAME=${EXEPATH}/fogchains_dbg
else
    # echo "debug mode off"
    EXENAME=${EXEPATH}/fogchains
fi
${EXENAME} -n ${SIMPATH}:${SRCPATH} $*
# for shared lib, use: opp_run -l ../src/fogchains -n ${SIMPATH}:${SRCPATH} $*
